-- MySQL Script generated by MySQL Workbench
-- Mon Apr  5 20:41:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema se3330
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema se3330
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `se3330` DEFAULT CHARACTER SET utf8 ;
USE `se3330` ;

-- -----------------------------------------------------
-- Table `se3330`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_employee` TINYINT NOT NULL DEFAULT 0,
  `email` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `opt_out_email` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`doctor` (
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_doctor_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `se3330`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`patient` (
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_patient_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `se3330`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`illness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`illness` (
  `illness_id` INT NOT NULL AUTO_INCREMENT,
  `illness_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`illness_id`),
  UNIQUE INDEX `illness_name_UNIQUE` (`illness_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL,
  `doctor_person_id` INT NOT NULL,
  `patient_person_id` INT NOT NULL,
  `illness_id` INT NOT NULL,
  `check_in_status` VARCHAR(45) NOT NULL DEFAULT 'Not Checked In',
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_doctor1_idx` (`doctor_person_id` ASC) VISIBLE,
  INDEX `fk_appointment_patient1_idx` (`patient_person_id` ASC) VISIBLE,
  INDEX `fk_appointment_illness1_idx` (`illness_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_doctor1`
    FOREIGN KEY (`doctor_person_id`)
    REFERENCES `se3330`.`doctor` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`patient_person_id`)
    REFERENCES `se3330`.`patient` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_illness1`
    FOREIGN KEY (`illness_id`)
    REFERENCES `se3330`.`illness` (`illness_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`patient` (
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_patient_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `se3330`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`employee` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `se3330`.`patient_has_illness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `se3330`.`patient_has_illness` (
  `patient_person_id` INT NOT NULL,
  `illness_illness_id` INT NOT NULL,
  PRIMARY KEY (`patient_person_id`, `illness_illness_id`),
  INDEX `fk_patient_has_illness_illness1_idx` (`illness_illness_id` ASC) VISIBLE,
  INDEX `fk_patient_has_illness_patient1_idx` (`patient_person_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_has_illness_patient1`
    FOREIGN KEY (`patient_person_id`)
    REFERENCES `se3330`.`patient` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_has_illness_illness1`
    FOREIGN KEY (`illness_illness_id`)
    REFERENCES `se3330`.`illness` (`illness_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


## ------------------------- DATA INSERTS ------------------------- ##

INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Employee', 'Test', 'testemployee', 'password', 1, 'se3330nullpointerexception@gmail.com', 50);
INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Ryan', 'Cherry', 'cherryryan', 'cherrypass', 0, 'cherryry@uwplatt.edu', 21);
INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Ryan', 'Sievert', 'sievertryan', 'sievertpass', 0, 'sievertr@uwplatt.edu', 20);
INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Hunter', 'Liddell', 'liddellhunter', 'liddellpass', 0, 'liddellh@uwplatt.edu', 20);
INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Mathiah', 'Draeger', 'draegermathiah', 'draegerpass', 0, 'draegerm@uwplatt.edu', 20);
INSERT INTO person (first_name, last_name, username, password, is_employee, email, age) VALUES ('Luqmaan', 'Jung', 'jungluqmaan', 'jungpass', 0, 'jungl@uwplatt.edu', 20);

INSERT INTO illness (illness_name) VALUES ('Headache');
INSERT INTO illness (illness_name) VALUES ('Stomache Ache');
INSERT INTO illness (illness_name) VALUES ('Fever');
INSERT INTO illness (illness_name) VALUES ('Nausea');
INSERT INTO illness (illness_name) VALUES ('Coughing');

INSERT INTO doctor VALUES (1);
INSERT INTO patient VALUES(2);
INSERT INTO patient VALUES(3);
INSERT INTO patient VALUES(4);
INSERT INTO patient VALUES(5);
INSERT INTO patient VALUES(6);

INSERT INTO appointment (time, doctor_person_id, patient_person_id, illness_id) VALUES ('2021-04-05 03:14:07.00', 1, 2, 1);
INSERT INTO appointment (time, doctor_person_id, patient_person_id, illness_id) VALUES ('2021-04-05 05:05:56.00', 1, 3, 2);
INSERT INTO appointment (time, doctor_person_id, patient_person_id, illness_id) VALUES ('2021-04-06 07:43:34.00', 1, 4, 3);
INSERT INTO appointment (time, doctor_person_id, patient_person_id, illness_id) VALUES ('2021-04-06 02:12:31.00', 1, 5, 4);
INSERT INTO appointment (time, doctor_person_id, patient_person_id, illness_id) VALUES ('2021-04-07 11:17:11.00', 1, 6, 5);

